### ISSUE TITLE
Chat with Oliver and Library Jeff

### ISSUE THREAD

**Issue by DakotaNelson** [olin/register#4]
Hack the Library may have some interest in helping out with this app, Oliver and Jeff are worth checking in with (also, they're setting up Heroku hosting run by the library for apps like this, so at the least you may be able to get some 'o dat).

Long version: Jeff is really interested in having the library expand into the digital realm, and wants to be able to host a bunch of Olin infrastructure as part of a digital services initiative. Oliver and Jeff are working together on this.

**Comment by billmwong** [comment]
Hmm okay, Oliver is the Olin.js technical advisor so we can talk to him about this during our next meeting.

**Comment by billmwong** [comment]
We've been in some contact with the library, Jeff has other stuff he's doing this summer but maybe next semester we'll work more closely with them.
